# Converts a SPIR-V binary into a C++ header with a uint32_t array.
#   cmake -DINPUT=x.spv -DOUTPUT=x.spv.h -DVAR=kSpv_x -P EmbedSpirv.cmake
# SPIR-V is a stream of little-endian 32-bit words; the bytes are regrouped
# into words with one regex pass (fast even for large shaders).

if(NOT INPUT OR NOT OUTPUT OR NOT VAR)
  message(FATAL_ERROR "EmbedSpirv: INPUT, OUTPUT and VAR are required")
endif()

file(READ "${INPUT}" hex HEX)
string(LENGTH "${hex}" hexLen)
math(EXPR rem "${hexLen} % 8")
if(hexLen EQUAL 0 OR NOT rem EQUAL 0)
  message(FATAL_ERROR "EmbedSpirv: ${INPUT} is not a valid SPIR-V file")
endif()
math(EXPR wordCount "${hexLen} / 8")

set(b "([0-9a-f][0-9a-f])")
string(REGEX REPLACE "${b}${b}${b}${b}" "0x\\4\\3\\2\\1u," words "${hex}")
# 8 words per line keeps lines short for every compiler.
string(REGEX REPLACE "(0x[0-9a-f]+u,0x[0-9a-f]+u,0x[0-9a-f]+u,0x[0-9a-f]+u,0x[0-9a-f]+u,0x[0-9a-f]+u,0x[0-9a-f]+u,0x[0-9a-f]+u,)"
       "\\1\n  " words "${words}")

file(WRITE "${OUTPUT}"
  "// Generated by EmbedSpirv.cmake from ${INPUT}. Do not edit.\n"
  "#pragma once\n#include <cstdint>\n#include <cstddef>\n"
  "inline constexpr uint32_t ${VAR}[${wordCount}] = {\n  ${words}\n};\n"
  "inline constexpr size_t ${VAR}_size = sizeof(${VAR});\n")
