#pragma once

// Client side of the game protocol: wraps an AttomeNet 2 Host, encodes and
// decodes Protocol.h messages, and hands decoded messages to a handler.

#include "shared/Protocol.h"

#include "../../../engine/net2/Net.h"

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace ao::client {

class NetHandler {
public:
  virtual ~NetHandler() = default;
  virtual void onConnected() {}
  virtual void onDisconnected(atm::net2::DisconnectReason) {}
  virtual void onWelcome(const proto::Welcome &) {}
  virtual void onChunkData(const proto::ChunkData &) {}
  virtual void onEditedChunks(const proto::EditedChunks &) {}
  virtual void onBlockChanged(const proto::BlockChanged &) {}
  virtual void onSnapshot(const proto::SnapshotMsg &) {}
  virtual void onAppearance(const proto::AppearanceMsg &) {}
  virtual void onDamage(const proto::DamageEvent &) {}
  virtual void onInventory(const proto::InventoryMsg &) {}
  virtual void onXpGain(const proto::XpGain &) {}
  virtual void onLoot(const proto::LootMsg &) {}
  virtual void onChat(const proto::ChatMsg &) {}
};

class NetClient {
public:
  NetClient();
  ~NetClient();

  bool connect(const std::string &host, uint16_t port, std::string *error);
  void disconnect();

  // Pumps the transport and dispatches decoded messages to `handler`.
  void update(NetHandler &handler);

  bool connected() const { return connected_; }
  atm::net2::PeerStats stats() const;

  // Sends a message on the given channel. Returns false if not connected or
  // the transport queue is full.
  template <class M>
  bool send(const M &msg, atm::net2::Channel channel) {
    if (!connected_)
      return false;
    scratch_.clear();
    atm::net2::BitWriter w(scratch_);
    w.varu(M::kId);
    encode(w, msg); // generated by ATM_DEFINE_MESSAGE (found by ADL)
    if (w.overflow())
      return false;
    return host_->send(server_, channel, scratch_);
  }

  uint64_t bytesIn() const { return bytesIn_; }
  uint64_t bytesOut() const;

private:
  void dispatch(std::span<const uint8_t> data, NetHandler &handler);

  std::unique_ptr<atm::net2::Host> host_;
  atm::net2::PeerId server_;
  bool connected_ = false;
  std::vector<uint8_t> scratch_;
  uint64_t bytesIn_ = 0;
};

} // namespace ao::client
